apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: shuklajazurevotingappredis 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shuklajazurevotingappredis 
    spec:
      containers:
        - name: shuklajazurevotingappredis 
          image: sanimages.azurecr.io/shuklajazurevotingappredis
          ports:
          - containerPort: 80